"""Add user profile fields

Revision ID: fe0e4967fb04
Revises: f20f3b2ef964
Create Date: 2026-01-29 08:45:37.194362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0e4967fb04'
down_revision = 'f20f3b2ef964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interested_in_13hp', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')
        batch_op.drop_column('interested_in_13hp')

    # ### end Alembic commands ###
